apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 10
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: alexwang2020/helloworld-go
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1000m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"