# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: perf-test-sa
#   # namespace: perf-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: perf-test-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: perf-test-rb
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: perf-test-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: perf-test-role
  apiGroup: rbac.authorization.k8s.io