apiVersion: batch/v1
kind: Job
metadata:
  name: merge-perf-test-results
  # namespace: perf-test
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        name: merge-perf-test-results
    spec:
      serviceAccountName: perf-test-sa
      initContainers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: poll-job-results
        command: ["/scripts/script.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: merge-perf-test-results
        command: ["/bin/sh", "-c"]
        args: ["sh /scripts/start.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 2000Mi
      volumes:
      - name: script
        configMap:
          name: poll-script
          defaultMode: 0744
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poll-script
  # namespace: perf-test
data:
  script.sh: |
    #!/bin/sh
    # until [ $(kubectl get job perf-test -n perf-test -o=jsonpath='{.status.conditions[0].type}') = "Complete" ];
    until [ $(kubectl get job perf-test -o=jsonpath='{.status.conditions[0].type}') = "Complete" ];
    do
      echo .
      sleep 10;
    done

  start.sh: |
    BUCKET_NAME="perf-test-aws"
    SCENARIO_NAME="TEST"
    mkdir -p $SCENARIO_NAME
    cd $SCENARIO_NAME
    aws s3 cp s3://$BUCKET_NAME/$SCENARIO_NAME ./ --recursive
    gatling -ro $(pwd)
    rm *.log
    cd ../
    tar -zcvf report.tar.gz ./$SCENARIO_NAME
    aws s3 cp report.tar.gz s3://$BUCKET_NAME/$SCENARIO_NAME/report.tar.gz